### ISSUE TITLE
Support for new Thunderbird versions

### ISSUE THREAD

**Issue by maciejjo** [vanto/tb-personal-level-indicator#10]
Hi, I have TB 31.4.0 installed, and while the extension installs OK, it doesn't add any columns to the column menu. Any chance it can be upgraded for newer versions?

**Comment by vanto** [comment]
I have the same version and it works flawlessly. In any case the column needs to be added manually via the "Select columns to display" button at the upper right of the table header. Does it show up in this list?

**Comment by maciejjo** [comment]
No, I dont. For me it looks like this:
![menu](https://cloud.githubusercontent.com/assets/3521861/6203090/3e698862-b50e-11e4-9da5-64b0b565c77c.png)

**Comment by vanto** [comment]
Sounds odd. Can you try to open the add-on options on the addons page to see if it shows the presentation radio buttons (there should be the option to choose between GMail style and Triple Style), one of them should be selected. Could you also look at the "Error Console" via the Tools Menu if there is anything suspicious? Thanks.

**Comment by vanto** [comment]
Cannot reproduce. Please open if the problem persists.
